export const PRESET_THEMES = [
    {
        id: 'midnight-professional',
        name: 'Midnight Professional',
        isActive: true,
        isCustom: false,
        colors: {
            primary: '#6366f1',
            secondary: '#8b5cf6',
            accent: '#a855f7',
            background: '#0a0a0a',
            surface: '#18181b',
            surfaceHover: '#27272a',
            text: '#fafafa',
            textSecondary: '#d4d4d8',
            textMuted: '#a1a1aa',
            border: '#3f3f46',
            divider: '#27272a',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#3b82f6',
        },
        fonts: {
            heading: 'Inter, sans-serif',
            body: 'Roboto, sans-serif',
            mono: 'JetBrains Mono, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.25rem',
            md: '0.5rem',
            lg: '0.75rem',
            xl: '1rem',
        },
        shadows: {
            sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
            md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
            lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
            xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        },
        images: {},
    },

    {
        id: 'ocean-breeze',
        name: 'Ocean Breeze',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#0ea5e9',
            secondary: '#06b6d4',
            accent: '#22d3ee',
            background: '#f0f9ff',
            surface: '#ffffff',
            surfaceHover: '#e0f2fe',
            text: '#0c4a6e',
            textSecondary: '#075985',
            textMuted: '#0369a1',
            border: '#bae6fd',
            divider: '#e0f2fe',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#0ea5e9',
        },
        fonts: {
            heading: 'Outfit, sans-serif',
            body: 'Open Sans, sans-serif',
            mono: 'Fira Code, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.375rem',
            md: '0.625rem',
            lg: '0.875rem',
            xl: '1.125rem',
        },
        shadows: {
            sm: '0 1px 3px 0 rgba(14, 165, 233, 0.1)',
            md: '0 4px 6px -1px rgba(14, 165, 233, 0.1)',
            lg: '0 10px 15px -3px rgba(14, 165, 233, 0.1)',
            xl: '0 20px 25px -5px rgba(14, 165, 233, 0.1)',
        },
        images: {},
    },

    {
        id: 'forest-calm',
        name: 'Forest Calm',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#10b981',
            secondary: '#059669',
            accent: '#34d399',
            background: '#f0fdf4',
            surface: '#ffffff',
            surfaceHover: '#dcfce7',
            text: '#064e3b',
            textSecondary: '#065f46',
            textMuted: '#047857',
            border: '#bbf7d0',
            divider: '#dcfce7',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#3b82f6',
        },
        fonts: {
            heading: 'Inter, sans-serif',
            body: 'Source Sans Pro, sans-serif',
            mono: 'Source Code Pro, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.25rem',
            md: '0.5rem',
            lg: '0.75rem',
            xl: '1rem',
        },
        shadows: {
            sm: '0 1px 2px 0 rgba(16, 185, 129, 0.05)',
            md: '0 4px 6px -1px rgba(16, 185, 129, 0.1)',
            lg: '0 10px 15px -3px rgba(16, 185, 129, 0.1)',
            xl: '0 20px 25px -5px rgba(16, 185, 129, 0.1)',
        },
        images: {},
    },

    {
        id: 'sunset-warmth',
        name: 'Sunset Warmth',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#f97316',
            secondary: '#ea580c',
            accent: '#fb923c',
            background: '#fff7ed',
            surface: '#ffffff',
            surfaceHover: '#ffedd5',
            text: '#7c2d12',
            textSecondary: '#9a3412',
            textMuted: '#c2410c',
            border: '#fed7aa',
            divider: '#ffedd5',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#3b82f6',
        },
        fonts: {
            heading: 'Poppins, sans-serif',
            body: 'Lato, sans-serif',
            mono: 'Roboto Mono, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.5rem',
            md: '0.75rem',
            lg: '1rem',
            xl: '1.25rem',
        },
        shadows: {
            sm: '0 1px 3px 0 rgba(249, 115, 22, 0.1)',
            md: '0 4px 6px -1px rgba(249, 115, 22, 0.1)',
            lg: '0 10px 15px -3px rgba(249, 115, 22, 0.1)',
            xl: '0 20px 25px -5px rgba(249, 115, 22, 0.1)',
        },
        images: {},
    },

    {
        id: 'corporate-blue',
        name: 'Corporate Blue',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#2563eb',
            secondary: '#1e40af',
            accent: '#3b82f6',
            background: '#f8fafc',
            surface: '#ffffff',
            surfaceHover: '#f1f5f9',
            text: '#0f172a',
            textSecondary: '#1e293b',
            textMuted: '#475569',
            border: '#cbd5e1',
            divider: '#e2e8f0',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#2563eb',
        },
        fonts: {
            heading: 'IBM Plex Sans, sans-serif',
            body: 'Helvetica, sans-serif',
            mono: 'IBM Plex Mono, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.125rem',
            md: '0.25rem',
            lg: '0.375rem',
            xl: '0.5rem',
        },
        shadows: {
            sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
            md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
            lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
            xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        },
        images: {},
    },

    {
        id: 'monochrome-minimal',
        name: 'Monochrome Minimal',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#27272a',
            secondary: '#18181b',
            accent: '#52525b',
            background: '#fafafa',
            surface: '#ffffff',
            surfaceHover: '#f4f4f5',
            text: '#09090b',
            textSecondary: '#18181b',
            textMuted: '#71717a',
            border: '#e4e4e7',
            divider: '#f4f4f5',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#3b82f6',
        },
        fonts: {
            heading: 'Inter, system-ui, sans-serif',
            body: 'system-ui, sans-serif',
            mono: 'ui-monospace, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.125rem',
            md: '0.25rem',
            lg: '0.375rem',
            xl: '0.5rem',
        },
        shadows: {
            sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
            md: '0 2px 4px 0 rgba(0, 0, 0, 0.06)',
            lg: '0 4px 6px 0 rgba(0, 0, 0, 0.07)',
            xl: '0 8px 12px 0 rgba(0, 0, 0, 0.08)',
        },
        images: {},
    },

    {
        id: 'purple-haze',
        name: 'Purple Haze',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#a855f7',
            secondary: '#9333ea',
            accent: '#c084fc',
            background: '#1a1625',
            surface: '#2d2438',
            surfaceHover: '#3d3149',
            text: '#faf5ff',
            textSecondary: '#e9d5ff',
            textMuted: '#d8b4fe',
            border: '#581c87',
            divider: '#3d3149',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#a855f7',
        },
        fonts: {
            heading: 'Space Grotesk, sans-serif',
            body: 'DM Sans, sans-serif',
            mono: 'JetBrains Mono, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.375rem',
            md: '0.625rem',
            lg: '0.875rem',
            xl: '1.125rem',
        },
        shadows: {
            sm: '0 1px 3px 0 rgba(168, 85, 247, 0.2)',
            md: '0 4px 6px -1px rgba(168, 85, 247, 0.2)',
            lg: '0 10px 15px -3px rgba(168, 85, 247, 0.3)',
            xl: '0 20px 25px -5px rgba(168, 85, 247, 0.3)',
        },
        images: {},
    },

    {
        id: 'rose-gold',
        name: 'Rose Gold',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#f43f5e',
            secondary: '#e11d48',
            accent: '#fb7185',
            background: '#fff1f2',
            surface: '#ffffff',
            surfaceHover: '#ffe4e6',
            text: '#881337',
            textSecondary: '#9f1239',
            textMuted: '#be123c',
            border: '#fecdd3',
            divider: '#ffe4e6',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#3b82f6',
        },
        fonts: {
            heading: 'Playfair Display, serif',
            body: 'Raleway, sans-serif',
            mono: 'Courier New, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0.5rem',
            md: '0.75rem',
            lg: '1rem',
            xl: '1.5rem',
        },
        shadows: {
            sm: '0 1px 3px 0 rgba(244, 63, 94, 0.1)',
            md: '0 4px 6px -1px rgba(244, 63, 94, 0.1)',
            lg: '0 10px 15px -3px rgba(244, 63, 94, 0.15)',
            xl: '0 20px 25px -5px rgba(244, 63, 94, 0.2)',
        },
        images: {},
    },

    {
        id: 'neon-cyberpunk',
        name: 'Neon Cyberpunk',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#22d3ee',
            secondary: '#06b6d4',
            accent: '#c026d3',
            background: '#0c0a09',
            surface: '#1c1917',
            surfaceHover: '#292524',
            text: '#fafaf9',
            textSecondary: '#e7e5e4',
            textMuted: '#a8a29e',
            border: '#44403c',
            divider: '#292524',
            success: '#10b981',
            warning: '#fbbf24',
            error: '#ef4444',
            info: '#22d3ee',
        },
        fonts: {
            heading: 'Orbitron, sans-serif',
            body: 'JetBrains Mono, monospace',
            mono: 'Fira Code, monospace',
        },
        spacing: { scale: 1 },
        borderRadius: {
            sm: '0rem',
            md: '0.125rem',
            lg: '0.25rem',
            xl: '0.375rem',
        },
        shadows: {
            sm: '0 0 5px rgba(34, 211, 238, 0.3)',
            md: '0 0 10px rgba(34, 211, 238, 0.4)',
            lg: '0 0 20px rgba(34, 211, 238, 0.5)',
            xl: '0 0 30px rgba(34, 211, 238, 0.6)',
        },
        images: {},
    },

    {
        id: 'earthy-vintage',
        name: 'Earthy Vintage',
        isActive: false,
        isCustom: false,
        colors: {
            primary: '#92400e',
            secondary: '#78350f',
            accent: '#b45309',
            background: '#fef3c7',
            surface: '#fffbeb',
            surfaceHover: '#fef08a',
            text: '#451a03',
            textSecondary: '#713f12',
            textMuted: '#92400e',
            border: '#fde68a',
            divider: '#fef08a',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#dc2626',
            info: '#3b82f6',
        },
        fonts: {
            heading: 'Merriweather, serif',
            body: 'Georgia, serif',
            mono: 'Courier New, monospace',
        },
        spacing: { scale: 1.1 },
        borderRadius: {
            sm: '0.25rem',
            md: '0.375rem',
            lg: '0.5rem',
            xl: '0.75rem',
        },
        shadows: {
            sm: '0 1px 2px 0 rgba(146, 64, 14, 0.1)',
            md: '0 2px 4px 0 rgba(146, 64, 14, 0.15)',
            lg: '0 4px 8px 0 rgba(146, 64, 14, 0.2)',
            xl: '0 8px 16px 0 rgba(146, 64, 14, 0.25)',
        },
        images: {},
    },
] as const;
